spring:
   datasource:
       driverClassName: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://database-1.cpftqip0azyx.ap-south-1.rds.amazonaws.com:3306/watercanapp_order_db
       username: prod_user
       password: prod_user
   flyway:
       driverClassName: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://database-1.cpftqip0azyx.ap-south-1.rds.amazonaws.com:3306/watercanapp_order_db
       username: prod_user
       password: prod_user